ecom/cart/urls.py
from django.conf.urls import *

urlpatterns = patterns('cart.views', (r'^$', 'show_cart', { 'template_name': 'cart/cart.html' }, 'show_cart'),
)

ecom/catalog/urls.py
from django.conf.urls import *

urlpatterns = patterns('views',
(r'^$', 'all', { 'template_name':'catalog/menu.html'}, 'catalog_home'),
(r'^product/(?P<product_slug>[-\w]+)/$', 'show_product', { 'template_name':'catalog/product.html'},'catalog_product'),
)

ecom/ecom/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
#from ecom.c
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'catalog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^catalog/', 'catalog.views.all', name='catalog'),

    url(r'^admin/', include(admin.site.urls)),

    #url(r'^cart/', include('cart.urls')),

    url(r'^cart/$', 'cart.views.show_cart', name='show_cart'),

    #url(r'^catalog/', include('catalog.urls')),

    url(r'^catalog/$', 'catalog.views.all', name='catalog_home'),

    url(r'^catalog/product/(?P<product_slug>[-\w]+)/$', 'catalog.views.show_product', name='catalog_product')
    #(r'^product/(?P<product_slug>[-\w]+)/$', 'show_product', { 'template_name':'catalog/product.html'},'catalog_product'),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/cart/models.py
from django.db import models

# Create your models here.
from catalog.models import Product

class CartItem(models.Model):
    cart_id = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)
    product = models.ForeignKey('catalog.Product', unique=False)

    class Meta:
        db_table = 'cart_items'
        ordering = ['date_added']
    def total(self):
        return self.quantity * self.product.price
    def name(self):
        return self.product.title
    def price(self):
        return self.product.price

    def augment_quantity(self, quantity):
        """ called when a POST request comes in for a Product instance already in the shopping cart """
        self.quantity = self.quantity + int(quantity)
        self.save()

ecom/catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
    slug = models.SlugField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_price(self):
        return self.price

    def get_absolute_url(self):
        return reverse('catalog_product', kwargs={"product_slug": self.slug})

class ProductImage(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to="catalog/images")
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.product.title

    def __str__(self):
        return self.product.title

ecom/catalog/forms.py
from django import forms
from catalog.models import Product

class ProductAddToCartForm(forms.Form):
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size':'2', 'value':'1', 'class':'quantity'}), 
                                  error_messages={'invalid':'Please enter a valid quantity.'}, 
                                  min_value=1)
    product_slug = forms.CharField(widget=forms.HiddenInput())
    
    def __init__(self, request=None, *args, **kwargs):
        """ override the default so we can set the request """
        self.request = request
        super(ProductAddToCartForm, self).__init__(*args, **kwargs)
    

ecom/cart/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from cart import cart

def show_cart(request):
    if request.method == 'POST':
        postdata = request.POST.copy()
        if postdata['submit'] == 'Remove':
            cart.remove_from_cart(request)
        if postdata['submit'] == 'Update':
            cart.update_cart(request)
    cart_items = cart.get_cart_items(request)
    page_title = 'Shopping Cart' 
    cart_subtotal = cart.cart_subtotal(request)
    context = {'cart_items': cart_items, 'page_title': page_title, 'cart_subtotal': cart_subtotal}
    template_name = 'cart/cart.html'
    #return render_to_response(template_name, locals(), context_instance=RequestContext(request))

    return render(request, template_name, context)

ecom/catalog/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from .forms import ProductAddToCartForm
from .models import Product
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from cart import cart

def home(request):
	if request.user.is_authenticated():
		username_is = "Jamal"
		context = {"username_is": request.user}
	else:
		context = {"username_is": request.user}
	
	template = 'base.html'	
	return render(request, template, context)

def all(request):
    products = Product.objects.all()
    context = {'products': products}
    template = 'catalog/menu.html'  
    return render(request, template, context)


def show_product(request, product_slug):
    template_name="catalog/product.html"
    print(product_slug)
    p = get_object_or_404(Product, slug=product_slug)
    page_title = p.title
    # evaluate the HTTP method, change as needed
    if request.method == 'POST':
        #create the bound form
        postdata = request.POST.copy()
        form = ProductAddToCartForm(request, postdata)
        #check if posted data is valid
        if form.is_valid():
            #add to cart and redirect to cart page
            cart.add_to_cart(request)
            # if test cookie worked, get rid of it
            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            url = reverse('show_cart')
            return HttpResponseRedirect(url)
    else:
        #create the unbound form. Notice the request as a keyword argument
        form = ProductAddToCartForm(request=request, label_suffix=':')
    # assign the hidden input the product slug
    form.fields['product_slug'].widget.attrs['value'] = product_slug
    # set test cookie to make sure cookies are enabled
    request.session.set_test_cookie()
    #return render_to_response(template_name, locals(), context_instance=RequestContext(request))

    context = {'p': p, 'page_title': p.title, 'form': form}
    return render(request, template_name, context)

ecom/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Static Top Navbar Example for Bootstrap</title>

	  <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/navbar-static-top/navbar-static-top.css" rel="stylesheet">

    {% load static from staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />

    

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

  {% include 'navbar.html' %}

    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1> Hello {{ username_is }}</h1>
        <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>To see the difference between static and fixed top navbars, just scroll.</p>
        <p>
          <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
        </p>
      </div>

    </div> <!-- /container -->

    {% block content%}{%endblock%}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

ecom/templates/cart/cart.html
{% extends 'base.html' %}

{% block content %}


{% if cart_items %}
	{% for item in cart_items %}
		<h1>{{item.name}}</h1>
		<h1>{{item.total}}</h1>
	{% endfor %}
{% else %}
	FUCK
{% endif %}

{%endblock%}

ecom/templates/catalog/all.html
{% extends 'base.html' %}


{% block content %}
<ul>
{% for product in products %}
<li> {{ product.title }} {{ product.price }} </li>
{% endfor %}
</ul>
{% endblock %}

ecom/templates/catalog/menu.html
{% extends 'base.html' %}



{% block content %}

<div class='row'>

{% for product in products %}

		<div class='col-sm-3'>
			<div class='menu-item'>
			{% for item in product.productimage_set.all %}

			<img src="{{ MEDIA_URL }}{{ item.image }}" />
			

			{% endfor %}
			<a href='{{ product.get_absolute_url }}'>{{ product.title }}</a>
			
			{{ product.price }}
			</div>


		</div>

{% endfor %}

</div>

{% endblock %}

ecom/templates/catalog/product.html
{% extends 'base.html' %}

{% block content %}

		<div class='col-sm-3'>
		{% for item in p.productimage_set.all %}

		<img src="{{ MEDIA_URL }}{{ item.image }}" />
		

		{% endfor %}
		{{ p.id }}
		{{ p.title }}
		{{ p.price }}



		</div>


<h1>{{ p.title }}</h1>


<br /><br />
	<form method="post" action="." class="cart">
	{{ form.as_p }}
	<br />
	{% csrf_token %}
	<input type="submit" value="Add To Cart" name="submit" alt="Add To Cart" />
	</form>
	<div class="cb"></div>
<br /><br />
<div class="cb"><br /><br /></div>
<h3>Product Description</h3>
{{ p.description }}
{% endblock %}

ecom/templates/navbar.html
<!-- Static navbar -->
    <div class="navbar navbar-default navbar-custom navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CFE eCommerce</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Welcome</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="/catalog">Menu</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pull down <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/cart"><i class="glyphicon glyphicon-shopping-cart"></i>{% if not request.session.items_total %} Cart(0) {% else %} Cart({{ request.session.items_total }}) {% endif%}</a></li>
            <li><a href="./">Derp</a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

ecom/templates/tags/cart_box.html
{% with cart_item_count as cart_count %}
<a href="{% url show_cart %}">
Shopping Cart
<br />
{{ cart_count }} Item{{ cart_count|pluralize }}
</a>
{% endwith %}